BOT_NAME = "aoto_crawler"
SPIDER_MODULES = ["aoto_crawler.spiders"]
NEWSPIDER_MODULE = "aoto_crawler.spiders"
ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 8
CONCURRENT_REQUESTS_PER_DOMAIN = 4
DOWNLOAD_DELAY = 0.6
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0.8
AUTOTHROTTLE_MAX_DELAY = 6
AUTOTHROTTLE_TARGET_CONCURRENCY = 2.0
HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 86400
LOG_LEVEL = "INFO"
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
FEED_EXPORT_ENCODING = "utf-8"
DEFAULT_REQUEST_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36 AOTO-Materials-Crawler/1.0",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.6",
}
